# fly.toml app configuration file generated for ssrflyio-lingering-leaf-7530-lively-breeze-4466 on 2024-01-19T12:20:01-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ssrflyio-lingering-leaf-7530-lively-breeze-4466"
primary_region = "lax"

[build]

[deploy]
  release_command = ".fly/release.sh"

[env]
  MIGRATE_ON_BOOT = "true"
  PORT = "8910"
  REDWOOD_DISABLE_TELEMETRY = "1"

[[mounts]]
  source = "data"
  destination = "/data"
  auto_extend_size_threshold = 0

[http_service]
  internal_port = 8910
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
